### PR TITLE
fix: API breakage as reported by marketplace (#38)

### LINKED ISSUE #38: correct API breakage as reported by marketplace
image
image
image

### PR DESCRIPTION
**Pull request by adietish**
fixes #38

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/telemetry/ui/utils/NotificationGroupAdapter.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+import com.intellij.openapi.application.ApplicationInfo;
+import com.intellij.openapi.diagnostic.Logger;
+
+import java.lang.reflect.Constructor;
+import java.lang.reflect.InvocationTargetException;
+import java.lang.reflect.Method;
+
+
+/**
+ * This is a copy of the identical class in intellij-common to avoid depending on intellij-common for this class only.
```
Comment (adietish) [inline src/main/java/com/redhat/devtools/intellij/telemetry/ui/utils/NotificationGroupAdapter.java:27]: copying the adapter that exists in intellij-common to avoid depending on the lib may be worth discussions.
@jeffmaury, @lstocchi, @sbouchet: Thoughts?

**Review by jeffmaury — APPROVED** [review]
LGTM
